services:
  db:
    image: postgres
    env_file:
        - ./docker/.local.env
    ports:
      - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
        context: .
        dockerfile: docker/dev.Dockerfile
    env_file:
        - ./docker/.local.env
    entrypoint: ["bash", "scripts/dev.sh"]
    volumes:
      - .:/app
    ports:
        - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
volumes:
    pgdata:
